[graph]
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "wasm32-unknown-unknown"]
all-features = true
no-default-features = false

[advisories]
unmaintained = "workspace"
unsound = "workspace"
ignore = []

[licenses]
confidence-threshold = 0.93
allow = ["Apache-2.0", "BSD-3-Clause", "MIT", "Unicode-3.0"]
exceptions = []

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = []
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
